import "@/app/globals.css";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { ToastContainer } from "@/components/ui/toast";
import { ErrorBoundary } from "@/components/ErrorBoundary";

const pretendard = localFont({
  src: "../..//node_modules/pretendard/dist/web/static/woff2/Pretendard-Regular.woff2",
  display: "swap",
  weight: "400",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "청람보드",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          pretendard.className
        )}
      >
        <ErrorBoundary>
          {children}
          <ToastContainer />
        </ErrorBoundary>
      </body>
    </html>
  );
}
